# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "iconoclasm"
  s.version = "1.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sander Hartlage"]
  s.date = "2012-04-05"
  s.description = "Finds favorites icons for web pages on the world wide internets by checking the HTML head or the standard favicon location. Then, do with them what you will."
  s.email = "sander.hartlage@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/iconoclasm.rb",
    "lib/iconoclasm/downloader.rb",
    "lib/iconoclasm/errors.rb",
    "lib/iconoclasm/extractor.rb",
    "lib/iconoclasm/favicon.rb",
    "lib/iconoclasm/headers.rb",
    "spec/helper.rb",
    "spec/iconoclasm/downloader_spec.rb",
    "spec/iconoclasm/errors_spec.rb",
    "spec/iconoclasm/extractor_spec.rb",
    "spec/iconoclasm/favicon_spec.rb",
    "spec/iconoclasm/headers_spec.rb",
    "spec/iconoclasm_spec.rb"
  ]
  s.homepage = "http://github.com/sander6/iconoclasm"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Finds favicons and DESTROYS THEM (well, not really, but it will download and save them)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<typhoeus>, [">= 0"])
    else
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<typhoeus>, [">= 0"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<typhoeus>, [">= 0"])
  end
end

